# Generated by Django 5.0.1 on 2024-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('measurement_date', models.DateField()),
                ('measurement_time', models.TimeField()),
                ('temperature', models.FloatField()),
                ('sensor_name', models.CharField(max_length=100)),
                ('sensor_model', models.CharField(max_length=100)),
                ('sensor_group', models.CharField(max_length=100)),
                ('pressure', models.FloatField()),
                ('co2_level', models.FloatField()),
            ],
        ),
    ]
